mkdir build
cd build

set CMAKE_FLAGS=-DGBNCPUFEAT=ON
set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX%
set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX%
set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=%LIBRARY_LIB%
set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=%LIBRARY_BIN%
set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=%LIBRARY_LIB%
set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_BUILD_TYPE=Release
set CMAKE_FLAGS=%CMAKE_FLAGS% -DBUILD_SHARED_LIBS=ON

cmake -G "NMake Makefiles" %CMAKE_FLAGS% %SRC_DIR%
if errorlevel 1 exit /b 1

cmake --build . --target install
if errorlevel 1 exit /b 1

