{% set version = "7.4.0.beta1" %}

package:
  name: graphblas
  version: {{ version }}

source:
  url: https://github.com/DrTimothyAldenDavis/GraphBLAS/archive/v{{ version }}.tar.gz
  sha256: b2539efafb1e60ceb617848eaed74388bcd4bb8df771f7c00cff70e5dfe87e77

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("graphblas", max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - m4  # [not win]
  host:
    - llvm-openmp
  run:
    - llvm-openmp

test:
  commands:
    - test -f ${PREFIX}/include/GraphBLAS.h  # [not win]
    - test -f ${PREFIX}/lib/libgraphblas${SHLIB_EXT}  # [not win]
    - test ! -e ${PREFIX}/lib/libgraphblas.a  # [not win]

about:
  home: https://github.com/DrTimothyAldenDavis/GraphBLAS
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: SuiteSparse:GraphBLAS is a full implementation of the GraphBLAS standard

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - minrk
    - jayfurmanek
    - jim22k
    - eriknw
