{% set version = "3.1.1" %}

package:
  name: graphblas
  version: {{ version }}

source:
  url: http://faculty.cse.tamu.edu/davis/GraphBLAS/GraphBLAS-{{ version }}.tar.gz
  sha256: 06044169ce1b0016660f4d4511b9cfb377a6c26e807de316a6b130f50f069fe9

build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage("graphblas") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - m4
  host:
    - openmp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - openmp  # [linux]
    - llvm-openmp  # [osx]

test:
  commands:
    - test -f ${PREFIX}/include/GraphBLAS.h
    - test -f ${PREFIX}/lib/libgraphblas${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libgraphblas.a

about:
  home: http://faculty.cse.tamu.edu/davis/GraphBLAS.html
  license: Apache 2.0
  license_family: Apache
  license_file: Doc/License.txt
  summary: SuiteSparse:GraphBLAS is a full implementation of the GraphBLAS standard

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - minrk
    - jayfurmanek
