{% set version = "9.1.0" %}

package:
  name: graphblas
  version: {{ version }}

source:
  url: https://github.com/DrTimothyAldenDavis/GraphBLAS/archive/v{{ version }}.tar.gz
  sha256: f3e9c3abc5cc5a4d561f56c659c94f2d08058dc7ccdbe8cb92d8dc833b8ea6e0

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("graphblas", max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - m4  # [not win]
  host:
    - llvm-openmp
  run:
    - llvm-openmp

test:
  commands:
    - test -f ${PREFIX}/include/suitesparse/GraphBLAS.h  # [not win]
    - test -f ${PREFIX}/lib/libgraphblas${SHLIB_EXT}  # [not win]
    - test ! -e ${PREFIX}/lib/libgraphblas.a  # [not win]
    - test -f ${PREFIX}/lib/cmake/GraphBLAS/GraphBLASConfig.cmake  # [not win]

about:
  home: https://github.com/DrTimothyAldenDavis/GraphBLAS
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: SuiteSparse:GraphBLAS is a full implementation of the GraphBLAS standard

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - minrk
    - jayfurmanek
    - jim22k
    - eriknw
