{% set version = "7.4.1.beta3" %}

package:
  name: graphblas
  version: {{ version }}

source:
  url: https://github.com/DrTimothyAldenDavis/GraphBLAS/archive/v{{ version }}.tar.gz
  sha256: 0a5898997b5fc534c9f6d618c8f8ad7ccad73da14b208588f3f802adbb21df65

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("graphblas", max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - m4  # [not win]
  host:
    - llvm-openmp
  run:
    - llvm-openmp

test:
  commands:
    - test -f ${PREFIX}/include/GraphBLAS.h  # [not win]
    - test -f ${PREFIX}/lib/libgraphblas${SHLIB_EXT}  # [not win]
    - test ! -e ${PREFIX}/lib/libgraphblas.a  # [not win]

about:
  home: https://github.com/DrTimothyAldenDavis/GraphBLAS
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: SuiteSparse:GraphBLAS is a full implementation of the GraphBLAS standard

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - minrk
    - jayfurmanek
    - jim22k
    - eriknw
