# native osx-64 toolchain
# for use in -DGRAPHBLAS_CROSS_TOOLCHAIN_FLAGS_NATIVE
# CMake settings for 64-bit x86 Mac build host
set ( CMAKE_SYSTEM_PROCESSOR "${CMAKE_HOST_SYSTEM_PROCESSOR}" )
set ( CMAKE_C_COMPILER "$ENV{CC_FOR_BUILD}" )
set ( CMAKE_CXX_COMPILER "$ENV{CXX_FOR_BUILD}" )
# clear flags (hope!)
set ( CMAKE_C_FLAGS "" CACHE STRING "" FORCE )
set ( CMAKE_EXE_LINKER_FLAGS "" CACHE STRING "" FORCE )
set ( CMAKE_MODULE_LINKER_FLAGS "" CACHE STRING "" FORCE )
set ( CMAKE_SHARED_LINKER_FLAGS "" CACHE STRING "" FORCE )
set ( CMAKE_CROSSCOMPILING OFF )
